//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Highland.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        [Display(Name = "Mã User")]

        public int ID { get; set; }
        [Required(ErrorMessage = "Name not empty ...")]
        [Display(Name = "Tên User")]
        public string UserName { get; set; }
        [Display(Name = "Email User")]
        public string EmailUser { get; set; }
        [DisplayName("Vai trò")]
        public string UserRole { get; set; }
        [DisplayName("Nhập mật khẩu")]
        [Required(ErrorMessage = "Pass not empty ...")]
        [DataType(DataType.Password)]
        public string UserPass { get; set; }

        [NotMapped]
        [DataType(DataType.Password)]
        [Compare("UserPass")]
        [DisplayName("Nhập lại mật khẩu")]
        public string ConfirmPass { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }
    }

    }
